# -*- coding: utf-8 -*-
"""Diabetes_Mineria_de_datos_DESPLIEGUE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m17HBiGFvLthzowTvpcFLiw98swO_BiN

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

#Cargamos el modelo
import pickle
filename = 'modelo-class.pkl'
model_rf,variables,min_max_scaler = pickle.load(open(filename, 'rb'))

# #Cargamos los datos futuros
# data = pd.read_csv("datos_futuros.csv")
# data.head()

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de diabetes')

Gender = st.selectbox('Genero', ['1', '2'])
AGE = st.slider('Edad', min_value=25, max_value=77, value=30, step=1)
Urea = st.slider('Urea', min_value=1.1, max_value=26.4, value=10.2, step=0.2)
Cr = st.slider('Cr', min_value=6, max_value=800, value=30, step=1)
HbA1c = st.slider('HbA1c', min_value=0.9, max_value=14.6, value=10.0, step=0.5)
Chol = st.slider('Chol', min_value=0.0, max_value=9.5, value=2.0, step=0.5)
TG = st.slider('TG', min_value=0.6, max_value=8.7, value=10.0, step=0.2)
VLDL = st.slider('VLDL', min_value=0.4, max_value=4.0, value=0.4, step=0.2)
BMI = st.slider('BMI', min_value=19.0, max_value=43.25, value=30.0, step=1.2)


datos = [[Gender, AGE, Urea, Cr, HbA1c, Chol, TG, VLDL, BMI]]
data = pd.DataFrame(datos, columns=['Gender', 'AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'VLDL', 'BMI']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación debe ser igual al aprendizaje
data_preparada=data.copy()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

"""# Predicciones"""

#Hacemos la predicción con Ranfom Forest
Y_fut = model_rf.predict(data_preparada)
data['RF']=Y_fut
data.head()

data